### ISSUE TITLE
Help get wallet back 

### ISSUE THREAD

**Issue by Dillface36** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#616]
$ bitcoin-cli gettransaction "bb4362dec15e67d366088f5493c789f22fb4a604e767dae1f6a631687e2784aa"
{
  "amount": 0.00095000,
  "confirmations": 12,
  "blockhash": "0000000075a4c1519da5e671b15064734c42784eab723530a6ace83ca1e66d3f",
  "blockheight": 1780789,
  "blockindex": 132,
  "blocktime": 1594841768,
  "txid": "bb4362dec15e67d366088f5493c789f22fb4a604e767dae1f6a631687e2784aa",
  "walletconflicts": [
  ],
  "time": 1594841108,
  "timereceived": 1594841108,
  "bip125-replaceable": "no",
  "details": [
    {
      "address": "mmX7GUoXq2wVcbnrnFJrGKsGR14fXiGbD9",
      "category": "receive",
      "amount": 0.00095000,
      "label": "",
      "vout": 0
    }
  ],
  "hex": "020000000001011efcc3bf9950ac2ea08c53b43a0f8cc21e4b5564e205f996f7cadb7d13bb79470000000017160014c4ea10874ae77d957e170bd43f2ee828a8e3bc71feffffff0218730100000000001976a91441d83eaffbf80f82dee4c152de59a38ffd0b602188ac713b10000000000017a914b780fc2e945bea71b9ee2d8d2901f00914a25fbd8702473044022025ee4fd38e6865125f7c315406c0b3a8139d482e3be333727d38868baa656d3d02204b35d9b5812cb85894541da611d5cec14c374ae7a7b8ba14bb44495747b571530121033cae26cb3fa063c95e2c55a94bd04ab9cf173104555efe448b1bfc3a68c8f873342c1b00"
}
```[tasklist]
### Tasks
- [ ] https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/pull/613
- [ ] https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/pull/611
- [ ] https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/pull/615
- [ ] https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/issues/609
- [ ] https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/pull/607
- [ ] https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/pull/612
- [ ] https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/issues/606
- [ ] https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/pull/603
```

**Comment by Dillface36** [comment]
> $ bitcoin-cli gettransaction "bb4362dec15e67d366088f5493c789f22fb4a604e767dae1f6a631687e2784aa"
> 
> {
> 
>   "amount": 0.00095000,
> 
>   "confirmations": 12,
> 
>   "blockhash": "0000000075a4c1519da5e671b15064734c42784eab723530a6ace83ca1e66d3f",
> 
>   "blockheight": 1780789,
> 
>   "blockindex": 132,
> 
>   "blocktime": 1594841768,
> 
>   "txid": "bb4362dec15e67d366088f5493c789f22fb4a604e767dae1f6a631687e2784aa",
> 
>   "walletconflicts": [
> 
>   ],
> 
>   "time": 1594841108,
> 
>   "timereceived": 1594841108,
> 
>   "bip125-replaceable": "no",
> 
>   "details": [
> 
>     {
> 
>       "address": "mmX7GUoXq2wVcbnrnFJrGKsGR14fXiGbD9",
> 
>       "category": "receive",
> 
>       "amount": 0.00095000,
> 
>       "label": "",
> 
>       "vout": 0
> 
>     }
> 
>   ],
> 
>   "hex": "020000000001011efcc3bf9950ac2ea08c53b43a0f8cc21e4b5564e205f996f7cadb7d13bb79470000000017160014c4ea10874ae77d957e170bd43f2ee828a8e3bc71feffffff0218730100000000001976a91441d83eaffbf80f82dee4c152de59a38ffd0b602188ac713b10000000000017a914b780fc2e945bea71b9ee2d8d2901f00914a25fbd8702473044022025ee4fd38e6865125f7c315406c0b3a8139d482e3be333727d38868baa656d3d02204b35d9b5812cb85894541da611d5cec14c374ae7a7b8ba14bb44495747b571530121033cae26cb3fa063c95e2c55a94bd04ab9cf173104555efe448b1bfc3a68c8f873342c1b00"
> 
> }
> 
> ```[tasklist]
> 
> ### Tasks
> 
> - [ ] https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/pull/613
> 
> - [ ] https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/pull/611
> 
> - [ ] https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/pull/615
> 
> - [ ] https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/issues/609
> 
> - [ ] https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/pull/607
> 
> - [ ] https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/pull/612
> 
> - [ ] https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/issues/606
> 
> - [ ] https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/pull/603
> 
> ```
> 
>

**Comment by shannona** [comment]
We can't provide support for Bitcoin usage.
